version: '3.7'
services:
# nodeabc:
#        build:
#            context: ./nodeabc
#            dockerfile: Dockerfile
#            args:
#                SSH_ABC_USER: ${SSH_ABC_USER}
#                SSH_ABC_PASS: ${SSH_ABC_PASS}
#        container_name: nodeabc
#        hostname: nodeabc
#        networks:
#            app_net:
#               ipv4_address: 172.16.238.11
# nodexyz:
#         build:
#            context: ./nodexyz
#            dockerfile: Dockerfile
#            args:
#               SSH_XYZ_USER: ${SSH_XYZ_USER}
#               SSH_XYZ_PASS: ${SSH_XYZ_PASS}
#         container_name: nodexyz
#         hostname: nodexyz
#         networks:
#            app_net:
#               ipv4_address: 172.16.238.12
 alphaserver:
         build:
            context: ./alphaserver
            dockerfile: Dockerfile
            args:
               SSH_SERVER_USER: ${SSH_SERVER_USER}
               SSH_SERVER_PASS: ${SSH_SERVER_PASS}
         container_name: alphaserver
         hostname: alphaserver
         ports:
           - "5000:5000"
         networks:
            app_net:
               ipv4_address: 172.16.238.10
networks:
 app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
